name: "Windows"
on:
  pull_request:

defaults:
  run:
    shell: bash --noprofile --norc -x -eo pipefail {0}

jobs:
  default:
    name: "DefaultD"
    runs-on: windows-latest
    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Checkout nats.c
        uses: actions/checkout@v4

      - name: Build
        env:
          VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
        run: |
          cmake -B build -S . -NATS_BUILD_STREAMING=OFF
          cmake --build build --config Debug

      - name: Test
        run: |
          cd build
          ./bin/Debug/testsuite
